title: "Role of Advanced Technology Vehicles (ATVs) in Mitigating Transportation CO2 Emissions"
description: "Jeong Hun (JJ) Lee, Yiyeon Kim, William Barnes, Bandhan Patel"
theme: jekyll-theme-cayman
